### ISSUE TITLE
GPU memory usage

### ISSUE THREAD

**Issue by violet-zct** [anoopkunchukuttan/geomm#1]
Hi,

Could you provide how much memory is usually used for the MUSE data set and FastText embedding?
I encountered the following problem when running your code:

Using cuDNN version 7104 on context None
Mapped name None to device cuda1: TITAN X (Pascal) (0000:06:00.0)
Traceback (most recent call last):
  File "geomm.py", line 298, in <module>
    main()
  File "geomm.py", line 246, in main
    nbrhood_z2=cp.zeros(zw.shape[0])
  File "/home/xuezhem/anaconda2/envs/geomm/lib/python3.6/site-packages/cupy/creation/basic.py", line 147, in zeros
    a = cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 151, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1064, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1085, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 899, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 920, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 680, in cupy.cuda.memory._try_malloc
  File "cupy/cuda/memory.pyx", line 677, in cupy.cuda.memory._try_malloc
  File "cupy/cuda/memory.pyx", line 868, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 472, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 473, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 77, in cupy.cuda.memory.Memory.__init__
  File "cupy/cuda/runtime.pyx", line 214, in cupy.cuda.runtime.malloc
  File "cupy/cuda/runtime.pyx", line 137, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered

I am sure if this is caused by lack of memory or other problems. I am using Ubuntu 16.04.2 LTS and cuda is properly installed on the machine.

Thank you!

Chunting

**Comment by anoopkunchukuttan** [comment]
For MUSE dataset and FastText embedding, it takes around 1.6 GB. We generally restrict to 200,000 vocab items. What are the dictionary size and max_vocab in your case?

**Comment by violet-zct** [comment]
I used the same setting as in your demo script but somehow came across this error. I didn’t see the memory is used a lot but has this runtime error.

**Comment by Digo** [comment]
Hi @anoopkunchukuttan 

We are trying to use cuda-9.0 and python-3.6.8 to reproduce the results and encountered the error @violet-zct pasted above.  

Here are the related python package versions: 
```
cupy-cuda90==5.2.0
numpy==1.16.1
pygpu==0.7.6
pymanopt==0.2.3
scipy==1.2.0
Theano==1.0.3+2.g3e47d39ac.dirty
```

Is that possible that you can post your `pip freeze` results or `requirements.txt` such that we can run the code with the same dependencies? Thanks a lot!

**Comment by arjunbalgovind** [comment]
Hi @Digo and @violet-zct 

We used python-3.6.5 in our environment. 
Here are the python package versions from the `pip freeze` results.

    cupy-cuda90==4.4.1
    numpy==1.14.5
    pygpu==0.7.6
    pymanopt==0.2.3
    scipy==1.1.0
    Theano==1.0.2+2.gc449c8699

Let us know if the issue persists after using these dependencies.

**Comment by Digo** [comment]
@anoopkunchukuttan Thank you so much for the reply! Unfortunately, the issue persists after re-install those dependencies...

**Comment by anoopkunchukuttan** [comment]
As a workaround, you could try running on the CPU itself, by setting the THEANO flags appropriately.

**Comment by pratikjawanpuria** [comment]
Hi @violet-zct @Digo 

I have just added the complete requirements.txt file. Hence, a re-reinstallation could be tried based on this. Or as Anoop suggested, if the issue persist, CPU only execution is also an option. 

Regards,
Pratik

**Comment by Digo** [comment]
@anoopkunchukuttan @pratikjawanpuria Thanks a lot for the advice. We end up using CPU to run the experiments.

**Comment by pratikjawanpuria** [comment]
Closing the issue.
